esphome:
  name: medidor_co2_prueba1
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""
  services:
    - service: mhz19_calibrate_zero
      then:
        - mhz19.calibrate_zero: mhz19_1
        - delay: 60s


ota:
  password: ""

wifi:
  ssid: "gdm"
  password: !secret gdm_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Medidor Co2 Prueba1"
    password: !secret default_password

web_server:
  port: 80

captive_portal:

##CO2
uart:
  rx_pin: D2
  tx_pin: D3
  baud_rate: 9600

sensor:
  - platform: mhz19
    id: mhz19_1
    update_interval: 5s
    automatic_baseline_calibration: false
    co2:
      id: co2sensor
      name: "MH-Z19 CO2 Value"
      on_value:
        - if:
            condition:
              lambda: 'return x < 700;'
            then:
              - output.turn_on: led_bueno
              - output.turn_off: led_regular
              - output.turn_off: led_malo
        - if:
            condition:
              lambda: 'return (x >= 700) && (x < 1000);'
            then:
              - output.turn_off: led_bueno
              - output.turn_on: led_regular
              - output.turn_off: led_malo
        - if:
            condition:
              lambda: 'return x >= 1000;'
            then:
              - output.turn_off: led_bueno
              - output.turn_off: led_regular
              - output.turn_on: led_malo


      
# Example configuration entry
output:
  - platform: gpio
    pin: D5
    id: led_bueno

  - platform: gpio
    pin: D6
    id: led_regular

  - platform: gpio
    pin: D7
    id: led_malo
